# Change these first
owner: nikolasibalic # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Atom Calculator
    url: https://atomcalc.org
    maxResponseTime: 2000
  - name: LabBricks
    url: https://labbricks.com
    maxResponseTime: 1000
  - name: Science Web Services - QState
    url: https://sws.labbricks.com/qstate/
    maxResponseTime: 1000
  - name: ResearchX3D
    url: https://researchx3d.com
    maxResponseTime: 1500
  - name: Carte Event
    url: https://www.carteevent.com/
    maxResponseTime: 1000
  - name: Carte Event map
    url: https://map.carteevent.com/13/4147/2819.png
    maxResponseTime: 1000
  - name: Roundtable
    url: https://roundtable.researchx3d.com/
    maxResponseTime: 1000


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/24477754?v=4
  name: Service status
  introTitle: "Services maintained by Nikola Sibalic"
  introMessage: This is a status page which uses **real-time** data, and shows incidents and scheduled maintenance.
  navbar:
    - title: Homepage
      href: https://nikolasibalic.github.io
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration


assignees:
  - nikolasibalic
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/13 * * * *"
