# Change these first
owner: nikolasibalic # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Atom Calculator
    url: https://atomcalc.org
  - name: LabBricks
    url: https://en.wikipedia.org
  - name: Science Web Services - QState
    url: https://sws.labbricks.com/qstate/
  - name: ResearchX3D
    url: https://researchx3d.com
  - name: Carte Event
    url: https://www.carteevent.com/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/24477754?v=4
  name: Service status
  introTitle: "Services maintained by Nikola Sibalic"
  introMessage: This is a sample status page which uses **real-time** data, incidents and scheduled maitenance.
  navbar:
    - title: Homepage
      href: https://nikolasibalic.github.io
    - title: GitHub
      href: https://github.com/nikolasibalic

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
